import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-stone-900 text-stone-400 py-16">
      <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="text-center md:text-left">
              <div className="text-white font-serif font-bold text-2xl mb-2">BacTermFinder</div>
              <p className="text-sm">"A Comprehensive and General Bacterial Terminator Finder using a CNN Ensemble"</p>
          </div>
          <div className="flex gap-6 text-sm font-medium">
              <a href="#" className="hover:text-white transition-colors">Paper</a>
              <a href="https://github.com/BioinformaticsLabAtMUN/BacTermFinder" className="hover:text-white transition-colors">GitHub</a>
          </div>
      </div>
      <div className="text-center mt-12 text-xs text-stone-600">
          Based on research published in bioRxiv (2024). Generated by AI.
      </div>
    </footer>
  );
};

export default Footer;